#for your two users, add profile_picture="url", user_lat=number, user_lng-number, user_radius=miles
# go to latlong.net enter 94501 USA -> gives coords
demo = User(
        username='Demo', email='demo@aa.io', password='password', profile_picture="https://di2ponv0v5otw.cloudfront.net/posts/2020/09/20/5f6826773bad6d1d4c21b86f/m_5f682683e107bbb1727114e0.jpg", user_lat=40.692532, user_lng=-73.990997, user_radius=25)
fremy = User(
        username='fremy', email='fremy@aa.io', password='password', profile_picture="https://scontent-atl3-1.xx.fbcdn.net/v/t1.6435-9/155157747_10158480330872058_2091608857930148729_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=UNIljRoawwYAX-6NeJb&_nc_ht=scontent-atl3-1.xx&oh=d7e66290459956118b7c2d42b8b3ad98&oe=6163C02A", user_lat=33.748997, user_lng=-84.387985, user_radius=15)


demo1 =Post(
        user_id=1, image_1="https://i.redd.it/xxepiu382g951.jpg", image_2="https://i.redd.it/3kt589cg05951.jpg", image_3="https://img.buzzfeed.com/buzzfeed-static/static/2020-06/30/23/asset/26d5c8999ab5/sub-buzz-8093-1593560895-28.jpg?resize=625:833", image_4="", image_5="", post_lat=40.653449, post_lng=-73.853692, description="This was my first rando-trek! rando-walk? idk what to call it but I found some cool and weird things on my walk. Took the red southbound train to Queens. ", like_count=number)
demo2=Post(
        user_id=1, image_1="https://i.imgur.com/FWHvyKF.jpg", image_2="url", image_3="url", image_4="url", image_5="url", post_lat=40.707450, post_lng=-74.093122, description="My friend and I went to thi abandonded warehouse. Don't ask us why, but we decided to go on the middle of the night. It was really creepy and we felt like we were being watched... probably wont go out this late again. Was only able to take one photo", like_count=number)
demo3=Post(
        user_id=1, image_1="https://i.redd.it/dlisyjw4i2n71.jpg", image_2="https://uncoveringpa.com/wp-content/uploads/2019/07/Scotia-2029.jpg", image_3="http://4.bp.blogspot.com/-OrXqY4cPaYE/VXhwE8BMIlI/AAAAAAAAArA/Y1W9dDow7eE/s1600/DSCF3517.JPG", image_4="https://uncoveringpa.com/wp-content/uploads/2019/07/Scotia-2036.jpg", image_5="url", post_lat=40.078071, post_lng=-74.399003, description="Went to go visit a friend in jersey and wanted to explore. We got sent to this super cool woodsy area where we saw all these forgotten stone buildings that had all this beautiful graffiti on it", like_count=number)
demo4=Post(
        user_id=1, image_1="https://i.ytimg.com/vi/9PSg30XfH0s/maxresdefault.jpg", image_2="https://saportakinsta.s3.amazonaws.com/wp-content/uploads/2018/02/zero-mile-post.jpg", image_3="", image_4="", image_5="", post_lat=40.905812, post_lng=-73.852145, description="I'm really beggining to like this app! I was sent to this sort of sketch area,but I kept my wits about me and my intentions clear(and my pepper spray close). The coordinates took me near some train tracks and I decided to see what and who was under there. I actually ended up talking to a really sweet homeless lady ,named Eldraih who ended up telling me how the city has change within the last thirty years. What an enriching experience!", like_count=number)
demo5=Post(
        user_id=1, image_1="https://preview.redd.it/aj3zv9v0aym71.jpg?width=640&crop=smart&auto=webp&s=518eaf935f66f59ea55b955a54a4cab747731860", image_2="", image_3="", image_4="", image_5="", post_lat=number, post_lng=number, description="Flash from the Past!!! This took us to an empty parking lot but look at this almost ancient Blockbuster sign! Didn't really find much else", like_count=number)
demo6=Post(
        user_id=1,  image_1="https://steemitimages.com/p/FxX5caie56yqUbvo2DTJv1i6qm8z4ixTabBTrjodAxvnU3ZLiCPFaYRgJ527Zvtww1VCCWERXrdE1JUQsNBzAMFcfhQuBZHZsiPYKDgBFLGe?format=match&mode=fit&width=1280", image_2="https://steemitimages.com/DQmU1vexkPNd7TrSHcy46M6U6AVFbFtzzWp9CauVBq9EQ6U/33.jpg",image_3="https://steemitimages.com/p/2923mN3pnd7PrxqAS8My84z8QnDpEsSBnKFsBYXvo94NNLva9x9yGKDnfrthbbunoMTKhKLiv9qNLnB3t42iBMcScCvBCS5qiT37rVjGh5nGdU?format=match&mode=fit&width=1280", image_4="https://steemitimages.com/DQmZe7evpSvkfvBiFEovzwquLEk6cnh8eJoPXLv1PjHfYFv/26.jpg", image_5="https://steemitimages.com/p/2923mN3pnd7PrxqAS8My84z8QnDpEsSBnKFsBYXvoCN1ZmVsm3DLRdnyo9Dz8Cvqjj9hxamWuj2N7B5fYf2qPjn8YgmxpGJsKZfpc1Ui5t74Rk?format=match&mode=fit&width=1280", post_lat=41.481391, post_lng=-72.686613, description="Went back home to see family in Connecticut, and was excited to hear my father express interest in going on an expidition with me. My father has been an avid explorer of sorts all of his life. Whether it was storage unit finds, or going to auctions, he was into it! Today we brought his metal detector on a misssion with us and found a what appeared to be a lot of WWII military equipment! What a great way to spend the day ", like_count=number)
demo7=Post(
        user_id=1, image_1="https://nancybird375.files.wordpress.com/2020/05/img_3073.jpg", image_2="https://pbs.twimg.com/media/C11mB6oUoAAqn5n.jpg", image_3="https://www.boredpanda.com/blog/wp-content/uploads/2019/06/interesting-forest-finds-116-5d0b7d9d2c7f1__700.jpg", image_4="https://www.maxpixel.net/static/photo/1x/Cute-Pet-Dog-Walk-Animal-Forest-Adorable-4863168.jpg", image_5="", post_lat=40.577812, post_lng=-74.150342, description="Just some Staten Island Find, took me to this trail near a park that had a lot of random things on it. Nice stroll for me and my dog though", like_count=number)
demo8=Post(
        user_id=1, image_1="https://dralegal.org/wp-content/uploads/2019/07/2019-NY-Sidewalks.jpg", image_2="", image_3="", image_4="", image_5="", post_lat=40.762896, post_lng=-74.100140, description="wasnt really anything here! I guess ALL the mission can't ALWAYS be amazing. Was also in kind of a blah mood, so that may have added to it. Brought me to ", like_count=number)

demo9=Post(
        user_id=1, image_1="https://cdn.newsday.com/polopoly_fs/1.50134407.1612124769!/httpImage/image.jpg_gen/derivatives/landscape_1280/image.jpg", image_2="https://preview.redd.it/uu7qbv5nutm71.jpg?width=640&crop=smart&auto=webp&s=379e3964a86b4d1bd5b5e896ccaec2cdda0c6352", image_3="https://cherisundra.files.wordpress.com/2017/06/golf-11.jpg", image_4="", image_5="", post_lat=40.822392, post_lng=-74.370663, description="OMG!!!! this has to be my coolest find yet! I believe my energy effected the find of my last mission. So today I decided to spend time meditating and thinking about good intentions before heading out. I also invited a few friends to increase the energy. We decided to go an hour out of brooklyn and found an abandoned mini-golf course!! It was so cool! We found some stones and played kick-kick (our version of put-put) lol ", like_count=number)
demo10=Post(
        user_id=1, image_1="https://preview.redd.it/sug9nm17dom71.jpg?width=960&crop=smart&auto=webp&s=e0d75a50e7b471dcfa032473323aa60309e3a73f", image_2="url", image_3="url", image_4="url", image_5="url", post_lat=40.658797, post_lng=-74.215221, description="This mission was as scary as the time I went at night to that abandoned warehouse with my friend in the middle of the night. Already ready , I logged in , got my mission and went off. I though I was another dead end because all I saw were trees however after 25 min of mindless walking I saw  what seemed to be a tunnel in the middle in the forest for god knows why. Anyway, something told me to stay back but I decided that if I was already out here , I was going to make the most of my trip.  I went in and turned on my phone flashlight to help with the light.I kept walking in and the echo sounded as if the tunnel was endless. I noticed that my phone was dying at a pretty alarming rate too so my truck couldn’t be too long. I decided to look on the floor, to which I saw countless things of people using the space momentarily. Broken bottles, condoms, syringes.. but then I saw that seem to be a markings on the wall along with candles and a pool of what looked like blood. As I attempted to take a picture of my phone completely died. I was only able to get a picture of the outside of the tunnel. I ran out of there immediately. That place gave me chills. Probably going to take a break from missions for a while…   ,", like_count=number)

fremy11= Post(
        user_id=2, image_1="https://preview.redd.it/j52d8uv4fom71.jpg?width=640&crop=smart&auto=webp&s=8e4c50c4edf2dfbff55431a83fefeef43d827a18", image_2="url", image_3="url", image_4="url", image_5="url", post_lat=33.752319, post_lng=-84.418902, description="This was my first mission, I went to this wooded area that ended up having a little creek behind it. Wasn't really anything noteworthy to snap a photo of, though I saw this weird barbed construction ", like_count=number)
fremy12= Post(
        user_id=2, image_1="https://www.gannett-cdn.com/presto/2019/10/21/PDTF/1d564a8e-d1df-43bf-bc3c-6c1010933734-Vacancy_2.jpg", image_2="https://www.toledoblade.com/image/2020/07/27/1140x_a10-7_cTC/CTY-BLUFF28-1.jpeg", image_3="url", image_4="url", image_5="url", post_lat=33.795697, post_lng=-84.331639, description="just a vacant lot , lol hoping to find something cool next time", like_count=number)
fremy13= Post(
        user_id=2, image_1="https://photos.thedyrt.com/photo/639586/media/georgia-cooper-creek-recreation-area_60f24dd3-335b-4515-a1b9-6289638042e1.jpeg?ixlib=rb-3.1.1&auto=webp", image_2="https://bilingualandmore.files.wordpress.com/2006/10/173_7316.JPG", image_3="https://flyfishingswva.files.wordpress.com/2019/10/f882f85e-bb59-4058-ad3d-b20947642588.jpg?w=1024", image_4="url", image_5="url", post_lat=33.717486, post_lng=-84.344434, description="Okay this was actually so peaceful! I actually saw this was near a nature reserve a friend of mine had been to, so I prepared for a hike. There was a gorgeous babbling creek with loads of wild life buzzing around. SO GLAD I went! lol I was beginning to lose faith in this site.  ", like_count=number)
fremy14= Post(
        user_id=2, image_1="https://saportakinsta.s3.amazonaws.com/wp-content/uploads/2018/02/gulch-2-KJ.jpg", image_2="https://saportakinsta.s3.amazonaws.com/wp-content/uploads/2018/02/gulch-3-KJ.jpg", image_3="https://saportakinsta.s3.amazonaws.com/wp-content/uploads/2018/02/zero-mile-post-2.jpg", image_4="url", image_5="url", post_lat=33.711793, post_lng=-84.393345, description="This brought me by the Mercedez Benz Stadium where the Georgia Dome used to be. I was kind of cool and sad to think about what had been here before hand. I love the culture of Atlanta", like_count=number)
fremy15= Post(
        user_id=2, image_1="https://i.imgur.com/lLZhoYS.jpeg", image_2="https://m.media-amazon.com/images/M/MV5BZmQ2Y2E2Y2EtN2QxOC00OWU0LTk1ZDYtY2JhZWQ2NDExYjY0XkEyXkFqcGdeQXVyMTEzNzczMA@@._V1_.jpg", image_3="https://m.media-amazon.com/images/M/MV5BMzQzOTBhYzItOWZhZC00ZjFiLWI4OGMtMzNjZTUzODJiNzdlXkEyXkFqcGdeQXVyMTEzNzczMA@@._V1_.jpg", image_4="url", image_5="url", post_lat=33.799424, post_lng=-84.428387, description="Okay so this was kinda creepy, I scoped the place out on google maps before going , and when I saw it was kind of in the middle of no where I called my homegirl to come with me. We walked for like 5 minutes and came up on this old abandonded house that was pretty intact. Some rooms still had some furniture and pictures. It was really weird , as if who ever stayed here before vanished in a flash. WOuld love to know what the story was here. ", like_count=number)


comment1 = Comment(
        post_id=16, user_id=1, comment="Wow! this looks really , interesting! you should check out some of my posts. I went on a similar mission recently. Keep posting great stuff!❤️ ")
comment1 = Comment(
        post_id=19, user_id=1, comment="Hmmm, do you mind explaining more about 1st picture? ")
comment1 = Comment(
        post_id=21, user_id=1, comment="OMG THAT'S AWESOME!!! would would've thought you could find such cool places on this site!?")

comment1 = Comment(
        post_id=1, user_id=2, comment="Girl, that shit look scary!! RUN!!!")
comment1 = Comment(
        post_id=1, user_id=2, comment="Oooo I went here with my ex once!")
comment1 = Comment(
        post_id=1, user_id=2, comment="The picture is kinda blurry ")
